name: Bug Report
description: Report unexpected behavior
assignees:
    - unwieldycat
labels: bug
body:
    - type: input
      id: environment-details
      attributes:
          label: Environment Details
          description: Details about your environment such as package version and node version.
          placeholder: 'v1.0.0, Node X.X, macOS 13'
    - type: textarea
      id: bug-details
      attributes:
          label: Bug Details
          description: What was the expected result? What was the actual result?
    - type: textarea
      id: steps-to-reproduce
      attributes:
          label: Steps to Reproduce
          description: A list of steps to reproduce the bug, and/or a code example.
