name: Enhancement
description: Suggest a change or an improvement
assignees:
    - unwieldycat
labels: enhancement
body:
    - type: textarea
      id: problem
      attributes:
          label: Problem
          description: The problem(s) the proposed enhancement addresses.
    - type: textarea
      id: proposal
      attributes:
          label: Proposal
          description: A description of the feature or enhancement to be added.
