name: Enhancement Suggestion
description: Suggest an enhancement or feature
assignees: 
  - unweildycat
labels: enhancement
title: '[Enhancement]:'
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: The problem(s) the proposed feature or enhancement addresses.
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: A description of the feature or enhancement to be added.