name: Question
description: A question about anything pertaining to the package
assignees:
    - unwieldycat
labels: question
body:
    - type: textarea
      id: question
      attributes:
          label: Question
          description: Please be sure to look through current or past issues to make sure your question is not a duplicate.
